### ISSUE TITLE
Chef Cookbook Compilation Error

### ISSUE THREAD

**Issue by michaelobriena** [tommyh/solo_wizard#11]
Not totally sure what is going wrong or why the script isn't providing the correct arguments to compile the chef cookbooks.  Any help would be appreciated.

std.out Below:

Michaels-MacBook-Pro:~ mike$ bash < <(curl -s http://www.solowizard.com/soloist_scripts/tbhs7v.sh )
~ ~
Password:
Successfully installed soloist-1.0.1
1 gem installed
Installing ri documentation for soloist-1.0.1...
Installing RDoc documentation for soloist-1.0.1...
Already up-to-date.
Already up-to-date.
Starting Chef Client, version 11.4.4
[2013-05-24T15:51:06-04:00] INFO: **\* Chef 11.4.4 ***
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
[2013-05-24T15:51:06-04:00] INFO: Setting the run_list to ["pivotal_workstation::ack", "pivotal_workstation::create_var_chef_cache", "pivotal_workstation::git", "pivotal_workstation::gitx", "pivotal_workstation::git_config_global_defaults", "pivotal_workstation::git_scripts", "pivotal_workstation::global_environment_variables", "pivotal_workstation::heroku_toolbelt", "pivotal_workstation::homebrew", "pivotal_workstation::imagemagick", "pivotal_workstation::iterm2", "pivotal_workstation::java", "pivotal_workstation::memcached", "pivotal_workstation::menumeters", "pivotal_workstation::mongodb", "pivotal_workstation::mysql", "pivotal_workstation::nginx", "pivotal_workstation::node_js", "pivotal_workstation::postgres", "pivotal_workstation::qt", "pivotal_workstation::redis", "pivotal_workstation::rvm", "pivotal_workstation::skype", "pivotal_workstation::sshd_on", "pivotal_workstation::sublime_text", "pivotal_workstation::tmux", "pivotal_workstation::unix_essentials", "pivotal_workstation::user_owns_usr_local", "pivotal_workstation::vim", "pivotal_workstation::vlc", "pivotal_workstation::workspace_directory"] from JSON
[2013-05-24T15:51:06-04:00] INFO: Run List is [recipe[pivotal_workstation::ack], recipe[pivotal_workstation::create_var_chef_cache], recipe[pivotal_workstation::git], recipe[pivotal_workstation::gitx], recipe[pivotal_workstation::git_config_global_defaults], recipe[pivotal_workstation::git_scripts], recipe[pivotal_workstation::global_environment_variables], recipe[pivotal_workstation::heroku_toolbelt], recipe[pivotal_workstation::homebrew], recipe[pivotal_workstation::imagemagick], recipe[pivotal_workstation::iterm2], recipe[pivotal_workstation::java], recipe[pivotal_workstation::memcached], recipe[pivotal_workstation::menumeters], recipe[pivotal_workstation::mongodb], recipe[pivotal_workstation::mysql], recipe[pivotal_workstation::nginx], recipe[pivotal_workstation::node_js], recipe[pivotal_workstation::postgres], recipe[pivotal_workstation::qt], recipe[pivotal_workstation::redis], recipe[pivotal_workstation::rvm], recipe[pivotal_workstation::skype], recipe[pivotal_workstation::sshd_on], recipe[pivotal_workstation::sublime_text], recipe[pivotal_workstation::tmux], recipe[pivotal_workstation::unix_essentials], recipe[pivotal_workstation::user_owns_usr_local], recipe[pivotal_workstation::vim], recipe[pivotal_workstation::vlc], recipe[pivotal_workstation::workspace_directory]]
[2013-05-24T15:51:06-04:00] INFO: Run List expands to [pivotal_workstation::ack, pivotal_workstation::create_var_chef_cache, pivotal_workstation::git, pivotal_workstation::gitx, pivotal_workstation::git_config_global_defaults, pivotal_workstation::git_scripts, pivotal_workstation::global_environment_variables, pivotal_workstation::heroku_toolbelt, pivotal_workstation::homebrew, pivotal_workstation::imagemagick, pivotal_workstation::iterm2, pivotal_workstation::java, pivotal_workstation::memcached, pivotal_workstation::menumeters, pivotal_workstation::mongodb, pivotal_workstation::mysql, pivotal_workstation::nginx, pivotal_workstation::node_js, pivotal_workstation::postgres, pivotal_workstation::qt, pivotal_workstation::redis, pivotal_workstation::rvm, pivotal_workstation::skype, pivotal_workstation::sshd_on, pivotal_workstation::sublime_text, pivotal_workstation::tmux, pivotal_workstation::unix_essentials, pivotal_workstation::user_owns_usr_local, pivotal_workstation::vim, pivotal_workstation::vlc, pivotal_workstation::workspace_directory]
[2013-05-24T15:51:06-04:00] INFO: Starting Chef Run for Michaels-MacBook-Pro.local
[2013-05-24T15:51:06-04:00] INFO: Running start handlers
[2013-05-24T15:51:06-04:00] INFO: Start handlers complete.
Compiling Cookbooks...
# 
# Recipe Compile Error in /Users/mike/cookbooks/dmg/resources/package.rb
## ArgumentError

wrong number of arguments (2 for 1)
## Cookbook Trace:

  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:42:in `const_defined?'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:42:in`build_from_file'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:208:in `load_lwrp_resource'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:193:in`load_lwrps_from_cookbook'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:192:in `each'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:192:in`load_lwrps_from_cookbook'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:120:in `compile_lwrps'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:119:in`each'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:119:in `compile_lwrps'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:72:in`compile'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/run_context.rb:86:in `load'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/client.rb:224:in`setup_run_context'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/client.rb:467:in `do_run'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/client.rb:200:in`run'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/application.rb:190:in `run_chef_client'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:239:in`run_application'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in `loop'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/application/solo.rb:231:in`run_application'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/application.rb:73:in `run'
  /Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/chef-solo:25
  /usr/bin/chef-solo:19:in`load'
  /usr/bin/chef-solo:19
## Relevant File Content:

/Library/Ruby/Gems/1.8/gems/chef-11.4.4/bin/../lib/chef/resource/lwrp_base.rb:

 35:  
 36:        # Evaluates the LWRP resource file and instantiates a new Resource class.
 37:        def self.build_from_file(cookbook_name, filename, run_context)
 38:          rname = filename_to_qualified_string(cookbook_name, filename)
 39:  
 40:          # Add log entry if we override an existing light-weight resource.
 41:          class_name = convert_to_class_name(rname)
 42>>         if Resource.const_defined?(class_name, false)
 43:            old_class = Resource.send(:remove_const, class_name)
 44:            # CHEF-3432 -- Chef::Resource keeps a list of subclasses; need to
 45:            # remove old ones from the list when replacing.
 46:            resource_classes.delete(old_class)
 47:            Chef::Log.info("#{class_name} light-weight resource already initialized -- overriding!")
 48:          end
 49:  
 50:          resource_class = Class.new(self)
 51:  

[2013-05-24T15:51:06-04:00] ERROR: Running exception handlers
[2013-05-24T15:51:06-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated
[2013-05-24T15:51:06-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-05-24T15:51:06-04:00] FATAL: ArgumentError: wrong number of arguments (2 for 1)

**Comment by nopium** [comment]
+1, same issue, ubuntu 12.04
